services:
  awscollector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    volumes:
      # Analyzer 以外で使用する予定がないため固定
      - ./analyzer-otel-config.yaml:/etc/otel-config.yaml
    command: ["--config=/etc/otel-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
