name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  analyzer-lint:
    defaults:
      run:
        shell: bash
        working-directory: ./app/analyzer
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: ./app/analyzer/go.mod
      - name: Run lint
        run: make lint
  analyzer-test:
    defaults:
      run:
        shell: bash
        working-directory: ./app/analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: ./app/analyzer/go.mod
      - name: Run test
        run: make test
